version: 2
snapshot:
  widths:
    - 320
    - 768
    - 1024
  minHeight: 800
  percyCSS: ""
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
static:
  cleanUrls: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
